### Cadastrar um nova categoria
POST https://localhost:5001/api/funcionario/create
Content-Type: application/json

{
    "Nome" : "Comida"
    "Idade" : 20
}

### Listar todas as categorias
GET https://localhost:5001/api/categoria/list